### ISSUE TITLE
For Frankfurt Meeting

### ISSUE THREAD

**Issue by rkrug** [IPBES-Data/IPBES_TCA_Corpus#7]
Type of analysis.

1. Here are some suggestions, feel free to add/modify them
2. Global maps showing

- [x]    1. The number of studies (e.g. per IPBES suregion) including transformative changes cases,
- [x]    2. Spatial and temporal analysis of the number of studies
- [ ]    3. Research topics (economics, social, biophysical, ILK), 
- [ ]    4. Scale (local, regional, national, indigenous territories, etc), 
- [ ]    5. Methods and indicators (monetary, biophysical, sociocultural) mainly used,
- [x] #8

9. Other suggestions?

**Comment by rkrug** [comment]
As I see it, the remaining ones (except of the Habitats (6) rely on full text analysis @niamir - correct?

One could use all available sub-fields and manually sort them into clusters relating to 3 and possibly 5, and analyse the topics of each work (all or only the main topic?) @niamir any opinion on that?

**Comment by rkrug** [comment]
Grouping of subfields into groups for 3 and 5: https://docs.google.com/spreadsheets/d/1ZCB_St2TQu_wL3yl1iN7Wxz5FERGxk-GZA0_2oGcRM0/edit?usp=sharing

**Comment by vikireyes** [comment]
Is there a way to check if the document refers to 1) conservation, 2) direct drivers of change, 3) indirect drivers of change, or 4) underlying causes?   To be transformative it has to address, somehow, 3 and 4

**Comment by rkrug** [comment]
Hi @vikireyes I do not think that is easily to do without an exhaustive full text analysis - any comments @niamir ?
